# Generated by Django 5.1.4 on 2025-03-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField()),
                ('caryear', models.IntegerField()),
                ('address', models.CharField()),
            ],
        ),
    ]
