# Generated by Django 5.1.4 on 2025-03-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displayapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='carname',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='caryear',
        ),
    ]
