# Generated by Django 5.1.4 on 2025-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayapp', '0002_remove_cardetails_address_remove_cardetails_carname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='car_address',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardetails',
            name='car_name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardetails',
            name='car_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardetails',
            name='car_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
